-- ================================================================
-- schema.sql -- Omada captive portal database schema
-- ================================================================
-- Target: SQLite (development) / PostgreSQL (Render.com production)
--
-- This file is written in SQLite syntax (AUTOINCREMENT).
-- The db/client.js layer's convertSchema() function translates
-- AUTOINCREMENT to GENERATED BY DEFAULT AS IDENTITY at runtime
-- when running against PostgreSQL.
-- The db/client.js layer also handles placeholder conversion (? -> $N).
--
-- Run with: node src/db/migrate.js
-- ================================================================

-- Voucher codes table
CREATE TABLE IF NOT EXISTS vouchers (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    code            VARCHAR(32) NOT NULL UNIQUE,
    type            VARCHAR(16) NOT NULL DEFAULT 'standard', -- 'standard' | 'premium'
    duration_minutes INTEGER NOT NULL DEFAULT 60,
    price           INTEGER, -- fixed price in centavos; NULL = use dynamic pricing
    state           VARCHAR(16) NOT NULL DEFAULT 'active',
    used_by_mac     VARCHAR(32),
    used_at         TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMP
);

-- Sessions table
CREATE TABLE IF NOT EXISTS sessions (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id          VARCHAR(32) NOT NULL UNIQUE,
    client_mac          VARCHAR(32) NOT NULL,
    ref_no              VARCHAR(64) UNIQUE,
    client_ip           VARCHAR(45),
    ap_mac              VARCHAR(32),
    ssid_name           VARCHAR(64),
    duration_minutes    INTEGER NOT NULL DEFAULT 60,
    voucher_type        VARCHAR(16) NOT NULL DEFAULT 'standard', -- 'standard' | 'premium'
    total_duration_seconds INTEGER, -- preserves original duration for premium remaining-time tracking
    started_at          TIMESTAMP,
    expires_at          TIMESTAMP,
    paused_at           TIMESTAMP,
    remaining_seconds   INTEGER,
    state               VARCHAR(16) NOT NULL DEFAULT 'pending',
    voucher_used        VARCHAR(32),
    provider_session_id VARCHAR(128),
    payment_event_id    VARCHAR(128),
    payment_amount      INTEGER,
    payment_method      VARCHAR(32),
    omada_auth_failed   BOOLEAN DEFAULT FALSE,
    expire_reason       VARCHAR(32),
    expired_at          TIMESTAMP,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Webhook events table
CREATE TABLE IF NOT EXISTS webhook_events (
        id           INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id     VARCHAR(128) NOT NULL UNIQUE,
    ref_no       VARCHAR(64) UNIQUE,
    session_id   VARCHAR(32),
        provider     VARCHAR(16),
    event_type   VARCHAR(64),
    amount       INTEGER,
    status       VARCHAR(16),
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------------
-- ref_no duplicate protection
-- Payment reference numbers are unique per transaction. SQLite
-- enforces this via the UNIQUE column constraint in each CREATE
-- TABLE above; PostgreSQL enforces it via the partial unique
-- indexes below (which also cover fresh production databases).
--
-- NOTE: these indexes reference ref_no, which does not exist on
-- legacy databases. migrate.js therefore runs column reconciliation
-- (migrate_fix.js) BEFORE applying this file, so the columns always
-- exist by the time these statements run.
-- ----------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_ref_no ON sessions(ref_no) WHERE ref_no IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_webhook_events_ref_no ON webhook_events(ref_no) WHERE ref_no IS NOT NULL;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sessions_state      ON sessions(state);
CREATE INDEX IF NOT EXISTS idx_sessions_client_mac ON sessions(client_mac);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_sessions_session_id ON sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_vouchers_code       ON vouchers(code);
CREATE INDEX IF NOT EXISTS idx_sessions_provider   ON sessions(provider_session_id);

-- Admin users
CREATE TABLE IF NOT EXISTS admin_users (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
    username      VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(16) DEFAULT 'admin',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login    TIMESTAMP
);

-- ================================================================
-- Portal client context
-- ================================================================
-- Controller context (AP MAC / SSID / radio ID) captured when a client
-- lands on the captive portal page, keyed by client MAC. The payment
-- webhook reads this row to authorize the client via extPortal/auth.
--
-- ASSUMPTION (single-site deployment): the lookup key is client_mac
-- alone. The `site` column records the site at capture time for future
-- collision detection only — see migrate_add_portal_context.js.
--
-- Staleness: rows older than PORTAL_CONTEXT_MAX_AGE_MS (config/index.js,
-- 1 hour) are treated as MISSING by the webhook (fail-loud
-- MISSING_PORTAL_CONTEXT path). seen_at is refreshed on every portal
-- page load by the landing beacon.
CREATE TABLE IF NOT EXISTS portal_client_context (
    client_mac  VARCHAR(32) PRIMARY KEY,
    client_ip   VARCHAR(45),
    ap_mac      VARCHAR(32) NOT NULL,
    ssid_name   VARCHAR(64) NOT NULL,
    radio_id    INTEGER NOT NULL DEFAULT 0,
    site        VARCHAR(64) NOT NULL DEFAULT 'Default',
    seen_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ================================================================
-- Notes:
--
-- 1. MAC addresses stored with colons (e.g. aa:bb:cc:dd:ee:ff).
--    Normalize on insert via normalizeMac().
--
-- 2. All timestamps are in UTC. Display in local time at frontend.
--
-- 3. Consider adding a batch table for bulk voucher generation,
--    or integrate directly with your point-of-sale / PMS system.
-- ================================================================
